#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

path_finder_program="$cmd_dir/path_finder"

echo "Running path_finder program 1 - pre made grid"
$path_finder_program -f "$cmd_dir/inputs/400V1400E.txt" -a all -o output1.txt || panic "path_finder program failed"

echo "Running path_finder program 2 - pre made grid"
$path_finder_program -f "$cmd_dir/inputs/10V100E.txt" -a all -o output2.txt || panic "path_finder program failed"

echo "Running path_finder program 3 - pre made grid"
$path_finder_program -f "$cmd_dir/inputs/20V30E.txt" -a all -o output3.txt || panic "path_finder program failed"

echo "Running path_finder program 4 - pre made grid"
$path_finder_program -f "$cmd_dir/inputs/30V200E.txt" -a all -o output4.txt || panic "path_finder program failed"

echo "Running path_finder program 5 - pre made grid"
$path_finder_program -f "$cmd_dir/inputs/100V500E.txt" -a all -o output5.txt || panic "path_finder program failed"

echo "Running path_finder program 6 - no path grid"
$path_finder_program -f "$cmd_dir/inputs/no_path.txt" -a all || panic "path_finder program failed"

echo "Note: you can modify the start and end nodes for any input file in ./inputs to your requirements"